---
- name: create misc. workspace directories
  file:
    state: directory
    path: "{{ user_home_dir }}/{{ item }}"
    group: "{{ target_group }}"
    owner: "{{ target_user }}"
    seuser: system_u
  loop:
    - .ansible/tmp
    - git
    - wkspc

- name: create SSH key for root user
  command: 'ssh-keygen -t ed25519 -N "" -C "root@localhost" -f /root/.ssh/id_ed25519'
  args:
    creates: "/root/.ssh/id_ed25519"

- name: clone dotfile repository from GitHub
  become: yes
  become_user: "{{ target_user }}"
  git:
    repo: "git@github.com:jwflory/swiss-army.git"
    dest: "{{ user_home_dir }}/git/swiss-army"
    update: no
    version: HEAD

- name: purge unused files
  file:
    path: "{{ user_home_dir }}/{{ item }}"
    state: absent
  loop:
    - .bash_completion.d/task.sh
