---
- name: install/upgrade EPEL and IUS repositories
  package:
    state: latest
    name:
      - epel-release
      - https://rhel7.iuscommunity.org/ius-release.rpm

- name: install base packages
  package:
    state: present
    name:
      - bash-completion
      - firewalld
      - fpaste
      - golang
      - htop
      - jq
      - pandoc
      - podman
      - rpmconf
      - smartmontools
      - strace
      - which
