language: python
python: "3.6"
install: "pip install yamllint"
script: "yamllint -c .yamllint ."

notifications:
  irc:
    channels:
      - "ircs://chat.freenode.net:6697/##jwf"
    template:
      - "[%{repository_name}:%{branch}@%{commit} - build #%{build_number}] CI %{result}! (%{build_url})"
    on_success: change
    on_failure: always
