---
- name: add git user config files
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ user_home_dir }}/.{{ item }}"
    group: "{{ target_user }}"
    owner: "{{ target_user }}"
  with_items:
    - gitconfig
    - gitconfig-jump
    - gitconfig-unicef
