---
- name: create misc. workspace directories
  file:
    state: directory
    path: "{{ user_home_dir }}/{{ item }}"
    group: "{{ target_user }}"
    owner: "{{ target_user }}"
  with_items:
    - .ansible/tmp
    - git
    - wkspc

- name: clone dotfile repository from GitHub
  become: yes
  become_user: "{{ target_user }}"
  git:
    repo: "https://github.com/jwflory/swiss-army.git"
    dest: "{{ user_home_dir }}/git/swiss-army"
