---
- name: remove unused packages
  package:
    state: absent
    name:
      - cmus
      - evolution
      - evolution-ews
      - evolution-help
      - gnome-classic-session
      - gnome-documents
      - gnome-documents-libs
      - gnome-system-monitor
      - gobby05
      - logwatch
      - mediawriter
      - mosh
      - origin-clients
      - planner
      - powerline
      - ntp
      - tmux-powerline
      - tomahawk

- name: add target user
  user:
    name: "{{ target_user }}"
    comment: "{{ target_user_name }}"
    groups: wheel
    append: yes
    generate_ssh_key: yes
    ssh_key_file: ".ssh/id_ed25519"
    ssh_key_type: ed25519

- name: create misc. workspace directories
  file:
    state: directory
    path: "{{ user_home_dir }}/{{ item }}"
    group: "{{ target_group }}"
    owner: "{{ target_user }}"
    mode: 0700
    seuser: system_u
  loop:
    - .ansible/tmp
    - git
    - wkspc

- name: clone dotfile repository from GitHub
  become: yes
  become_user: "{{ target_user }}"
  git:
    repo: "git@github.com:jwflory/swiss-army.git"
    dest: "{{ user_home_dir }}/git/swiss-army"
    accept_hostkey: yes
    update: no
    version: HEAD
  ignore_errors: yes

- name: download /etc/hosts file from someonewhocares.org
  get_url:
    url: https://someonewhocares.org/hosts/zero/hosts
    dest: /etc/hosts
    force: yes
    mode: 0644
    setype: net_conf_t
    seuser: system_u
