---
- name: import global variables
  include_vars:
    dir: "{{ inventory_dir }}/group_vars/"

- name: remove unused packages
  package:
    state: absent
    name:
      - evolution
      - evolution-ews
      - evolution-help
      - gnome-boxes
      - gnome-calendar
      - gnome-characters
      - gnome-classic-session
      - gnome-contacts
      - gnome-documents
      - gnome-documents-libs
      - gnome-getting-started-docs
      - gnome-initial-setup
      - gnome-maps
      - gnome-photos
      - gnome-shell-extension-pomodoro
      - gnome-system-monitor
      - gnome-weather
      - logwatch
      - mosh
      - powerline
      - python34
      - python34-libs
      - python34-pip
      - python34-setuptools
      - ntp
      - tmux-powerline
      - tomahawk

- name: add target user
  user:
    name: "{{ target_user }}"
    comment: "{{ target_user_name }}"
    groups: wheel
    append: yes
    generate_ssh_key: yes
