---
- name: import global variables
  include_vars:
    dir: "{{ inventory_dir }}/group_vars/"

- name: remove unused packages
  package:
    state: absent
    name:
      - evolution
      - evolution-ews
      - evolution-help
      - gnome-boxes
      - gnome-calendar
      - gnome-characters
      - gnome-classic-session
      - gnome-contacts
      - gnome-documents
      - gnome-documents-libs
      - gnome-getting-started-docs
      - gnome-initial-setup
      - gnome-maps
      - gnome-photos
      - gnome-shell-extension-pomodoro
      - gnome-system-monitor
      - gnome-weather
      - logwatch
      - mosh
      - powerline
      - python34
      - python34-libs
      - python34-pip
      - python34-setuptools
      - python36u
      - python36u-libs
      - python36u-pip
      - python36u-setuptools
      - ntp
      - tmux-powerline
      - tomahawk

- name: add target user
  user:
    name: "{{ target_user }}"
    comment: "{{ target_user_name }}"
    groups: wheel
    append: yes
    generate_ssh_key: yes

# gids/uids required for podman rootless mode
# https://github.com/jwflory/swiss-army/issues/11
- name: set multiple gids for target user
  lineinfile:
    path: "/etc/subgid"
    regexp: "^{{ target_user }}:"
    line: "{{ target_user }}:10000:65536"
    seuser: system_u

- name: set multiple uids for target user
  lineinfile:
    path: "/etc/subuid"
    regexp: "^{{ target_user }}:"
    line: "{{ target_user }}:10000:65536"
    seuser: system_u
