---
- name: add/upgrade RPM Fusion repositories
  package:
    state: latest
    name:
      - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm
      - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm

- name: remove unused packages
  package:
    state: absent
    name:
      - gnome-boxes
      - gnome-calendar
      - gnome-characters
      - gnome-contacts
      - gnome-font-viewer
      - gnome-getting-started-docs
      - gnome-initial-setup
      - gnome-maps
      - gnome-photos
      - gnome-weather

- name: install base packages
  ### Package notes ###
  # bat: cat(1) clone with wings
  # chromaprint-tools: Capture digital fingerprints of audio files
  # exfat-utils: FS formatting tools (exFAT)
  # f2fs-tools: FS formatting tools (Flash-Friendly File System)
  # gstreamer1-plugins-bad-nonfree: MPEG2 codec support
  # jpegoptim: Utility to optimize JPEG files
  # meld: Visual diff and merge tool
  # network-manager-applet: Network control / status applet for NetworkManager
  # remmina: Remote Desktop client
  # shotwell: Photo organizer and editor
  # poppler-utils: Command line utilities for converting PDF files
  # udftools: FS formatting tools (Universal Disk Format)
  package:
    state: present
    name:
      - https://dl.google.com/linux/direct/google-musicmanager-beta_current_x86_64.rpm
      - ansible
      - arandr
      - asciidoctor
      - bash-completion
      - bat
      - black
      - blueman
      - bpftrace
      - brasero
      - brasero-nautilus
      - chromaprint-tools
      - chromium
      - docker-compose
      - duply
      - epiphany
      - exfat-utils
      - f2fs-tools
      - feh
      - ffmpeg
      - fpaste
      - gnome-mahjongg
      - golang
      - golang-godoc
      - google-roboto-slab-fonts
      - gparted
      - gstreamer-ffmpeg
      - gstreamer1-plugins-bad-free-extras
      - gstreamer1-plugins-ugly
      - hexchat
      - htop
      - inkscape
      - java-11-openjdk
      - jpegoptim
      - jq
      - libvirt
      - libvirt-devel
      - lollypop
      - meld
      - mpris-scrobbler
      - mpv
      - nautilus-dropbox
      - network-manager-applet
      - nodejs-yarn
      - overpass-fonts
      - overpass-mono-fonts
      - pandoc
      - pavucontrol
      - picard
      - poppler-utils
      - powerline-fonts
      - pulseaudio-utils
      - remmina
      - rpmconf
      - shotwell
      - smartmontools
      - strace
      - telegram-desktop
      - typetype-molot-fonts
      - udftools
      - '@virtualization'
      - visualboyadvance-m
      - whipper
      - wireshark
      - yamllint
      - youtube-dl
