---
- name: add new groups - docker, libvirt
  group: name={{ item }}
  loop:
    - docker
    - libvirt

- name: add target user to new groups
  user:
    name: "{{ target_user }}"
    groups: docker,libvirt
    append: yes

- name: create or update permissions on /root/.ssh/
  file:
    path: /root/.ssh/
    state: directory
    owner: root
    group: root
    mode: 0700
    setype: ssh_home_t
    seuser: system_u

# Requires Ansible >= 2.8.
- name: create ed25519 SSH key for root user
  openssh_keypair:
    path: "/root/.ssh/id_ed25519"
    comment: "ansible-generated root@{{ ansible_hostname }}"
    type: ed25519
    seuser: system_u
