---
- name: copy repository configuration file for Fedora
  copy:
    src: slack.repo
    dest: /etc/yum.repos.d/slack.repo
    mode: 0644
    owner: root
    group: root
    setype: system_conf_t
    seuser: system_u

- name: install/upgrade slack
  package:
    state: latest
    name: slack
