---
- name: set up Justin's preferred CentOS 7.x Server configuration
  hosts: servers-centos
  become: yes

  roles:
    - { role: system/base, tags: ['base', 'system'] }
    - { role: system/centos-server, tags: ['centos', 'system'] }
    - { role: apps/base-server, tags: ['apps-base-server', 'apps'] }
    - { role: apps/bash, tags: ['bash', 'apps'] }
    - { role: apps/git, tags: ['git', 'apps'] }
    - { role: apps/npm, tags: ['npm', 'apps'] }
    - { role: apps/powerline-go, tags: ['powerline', 'apps'] }
    - { role: apps/ssh, tags: ['ssh', 'apps'] }
    - { role: apps/tmux, tags: ['tmux', 'apps'] }
    - { role: apps/vim, tags: ['vim', 'apps'] }
