---
- name: set up Justin's preferred Fedora Workstation configuration
  hosts: workstation
  become: yes

  roles:
    - system/base
    - system/fedora-workstation
    - system/packaging-tools
    - apps/base-workstation
    - apps/bash
    - apps/dunst
    - apps/git
    - apps/i3wm
    - apps/minecraft
    - apps/npm
    - apps/powerline-go
    - apps/ssh
    - apps/task
    - apps/thunderbird
    - apps/tmux
    - apps/tor
    - apps/vim
