---
- name: set up Justin's preferred RHEL/CentOS Workstation configuration
  hosts: workstation
  become: yes

  vars:
    ansible_python_interpreter: /usr/bin/python3
    target_group: jwf
    target_user: jwf
    target_user_name: Justin W. Flory
    user_home_dir: /home/jwf

  roles:
    - { role: system/base, tags: ['base', 'system'] }
    - { role: system/rhel-workstation, tags: ['rhel', 'system'] }
    # - { role: system/packaging-tools, tags: ['packaging-tools', 'system'] }
    - { role: system/python, tags: ['python', 'system'] }
    - { role: apps/bash, tags: ['bash', 'terminal', 'apps'] }
    # - { role: apps/dunst, tags: ['dunst', 'desktop', 'apps'] }
    - { role: apps/gcloud-sdk, tags: ['google-cloud', 'devops', 'apps'] }
    - { role: apps/git, tags: ['git', 'terminal', 'apps'] }
    - { role: apps/i3wm, tags: ['i3wm', 'desktop', 'apps'] }
    - { role: apps/npm, tags: ['npm', 'terminal', 'apps'] }
    - { role: apps/powerline-go, tags: ['powerline', 'terminal', 'apps'] }
    - { role: apps/protonvpn, tags: ['protonvpn', 'terminal', 'apps'] }
    - { role: apps/spotify, tags: ['spotify', 'desktop', 'apps'] }
    - { role: apps/ssh, tags: ['ssh', 'terminal', 'apps'] }
    - { role: apps/sublime-text, tags: ['sublime-text', 'desktop', 'apps'] }
    # - { role: apps/thunderbird, tags: ['thunderbird', 'desktop', 'apps'] }
    - { role: apps/tmux, tags: ['tmux', 'terminal', 'apps'] }
    # - { role: apps/tor, tags: ['tor', 'desktop', 'apps'] }
    - { role: apps/vim, tags: ['vim', 'terminal', 'apps'] }
