---
- name: set permissions on system bash_completion.d directory
  file:
    state: directory
    path: "/etc/bash_completion.d"
    mode: 0755
    setype: etc_t
    seuser: system_u

- name: push bashrc and bash_profile
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ user_home_dir }}/.{{ item }}"
    mode: 0400
    owner: "{{ target_user }}"
    group: "{{ target_group }}"
    setype: config_home_t
    seuser: system_u
  loop:
    - bashrc
    - bash_profile
